### ISSUE TITLE
big_table script creation fails

### ISSUE THREAD

**Issue by gravier** [snowplow/google-cloud-pubsub-example-project#5]
vagrant@huskimo:/vagrant$ inv create_bigtable_table --column-family=cf1 --instance-id=test-instance --region=us-west1-a --table-name=test-table
Traceback (most recent call last):
  File "/usr/local/bin/inv", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 270, in run
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 379, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python2.7/dist-packages/invoke/executor.py", line 114, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 113, in __call__
    result = self.body(*args, **kwargs)
  File "/vagrant/tasks.py", line 91, in create_bigtable_table
    instance.create()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/bigtable/instance.py", line 233, in create
    operation_pb = self._client._instance_stub.CreateInstance(request_pb)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.NOT_FOUND, us-west1-a zone not found)>

**Comment by uschen** [comment]
anyone knows what happened to us-west1 for bigtable?
